title: Universal Dependencies 日本語

email: masayu-a@ninjal.ac.jp

description: >- # this means to ignore newlines until "baseurl:"
  Universal Dependencies 日本語関連情報ページです。
  
baseurl: "/UD_Japanese-docs" 
url: "https://masayu-a.github.io/" 
twitter_username: masayu_a
github_username:  masayu-a

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: masayu_a
    github:  masayu-a

source:   .

destination: ./_site

markdown: kramdown

kramdown:
  enable_coderay: false

permalink:    date

markdown_ext: md

plugins:
   - jekyll-redirect-from

liquid:
   error_mode: warn

collections:
  ja:
    output: true
  u-overview:
    output: true
  u-pos:
    output: true
  u-dep:
    output: true
  u-feat:
    output: true
  includes:
    output: true


# URL configuration

home: "https://masayu-a.github.io/UD_Japanese-docs/"
tracker: "https://github.com/masayu-a/UD_Japanese-docs/issues"
git_raw: "https://github.com/masayu-a/UD_Japanese-docs"
git_edit: "https://github.com/universaldependencies/docs/edit/pages-source"
